export { CreateCommentDto } from './models/create-comment-dto';
export { RateMovieDto } from './models/rate-movie-dto';
export { AddToFavoritesDto } from './models/add-to-favorites-dto';
export { CreateUserDto } from './models/create-user-dto';
export { FollowDto } from './models/follow-dto';
export { Comment } from './models/comment';
export { Platform } from './models/platform';
export { Movie } from './models/movie';
export { User } from './models/user';
